In [5]:
from discovery_child_development import PROJECT_DIR, S3_BUCKET
from nesta_ds_utils.loading_saving import S3
import pandas as pd

ENRICHED_DATA_DIR = PROJECT_DIR / 'outputs/enrichments'
PATH_TO_DATASET = ENRICHED_DATA_DIR / 'openalex_patents_relevance_labels_only_relevant.csv'

In [6]:
patent_relevance = S3.download_obj(
    S3_BUCKET,
    f"data/outputs/binary_classifier/patents_openalex_random_sample_2019_labelled.csv",
    download_as="dataframe",
)

2024-05-31 17:17:45,670 - botocore.credentials - INFO - Found credentials in environment variables.

In [15]:
patent_relevance = patent_relevance.query("predictions == 1").assign(source = "patents")

In [16]:
len(patent_relevance)

26178

In [17]:
patent_relevance.to_csv(ENRICHED_DATA_DIR / 'patents_relevance_labels_only_relevant.csv', index=False)

In [13]:
patent_relevance.head(1)

,Unnamed: 0,id,text,predictions
18,18,CN-212289393-U,Baby carriage. A baby carriage comprises a rea...,1

In [10]:
patent_relevance_old = pd.read_csv(PATH_TO_DATASET).query("source == 'patents'")

In [11]:
len(patent_relevance_old)

12486

In [14]:
patent_relevance_old.head(1)

,Unnamed: 0,id,text,predictions,source
0,11,CN-107945066-A,Kindergarten intelligent control system and co...,1,patents