# GPT-generated summaries of category contents

In [44]:
import pandas as pd
from discovery_child_development import PROJECT_DIR, S3_BUCKET
import json

ENRICHED_DATA_DIR = PROJECT_DIR / 'outputs/enrichments'

In [161]:
OUTPUTS_DIR = ENRICHED_DATA_DIR / 'themes'
OUTPUTS_DIR.mkdir(exist_ok=True, parents=True)

In [66]:
from discovery_child_development.utils.openai_utils import client

In [4]:
relevant_df = pd.read_csv(ENRICHED_DATA_DIR / 'relevant_labelled_df.csv')

In [6]:
relevant_df.sample(2)

,id,text,Dataset,topics,Detection,Detection_,Management,Management_,year,country_code
7047,KR-20210072202-A,Method for Outputting Infants Emotional Condit...,Patents,"ai2, infancy",0.998998,1,0.069925,0,2021,KR
43524,W4294384666,Validation of the neurocognitive battery PreAc...,Publications,"preschool, cognitive",0.546417,1,0.301184,0,2022,NaN

In [27]:
# Path to topic information
PATH_TO_TOPICS = PROJECT_DIR / "discovery_child_development/pipeline/labelling/taxonomy_cat/prompts/topics.json"

# Load topic information
topics_dict = json.load(open(PATH_TO_TOPICS, 'r'))
topics = list(topics_dict.keys())
print(len(topics))

topics_df = []
for topic in topics_dict:
    topics_df.append({
        'topic': topic,
        'type': topics_dict[topic]['type'],
        'name': topics_dict[topic]['name'],
        # 'description': topics_dict[topic]['description']
    })
topics_df = (
    pd.DataFrame(topics_df)
    .sort_values(['type', 'topic',])
    .reset_index(drop=True)
    .replace('Family and home', 'Parenting')
    .rename(columns={'type': 'Type'})
)

38

In [28]:
topics_df.head()

           topic              Type                        name
0           arts  Area of learning  Expressive arts and design
1  communication  Area of learning  Communication and language
2      emotional  Area of learning   Personal social emotional
3       literacy  Area of learning                    Literacy
4    mathematics  Area of learning                 Mathematics

In [43]:
from discovery_child_development.getters.openalex import get_sentence_embeddings

# Path to sentence embeddings
VECTORS_PATH = "data/outputs/vectors/"
VECTORS_FILE = "sentence_vectors_384_labelled.parquet"

2024-04-23 11:06:03,494 - botocore.credentials - INFO - Found credentials in environment variables.
2024-04-23 11:06:05,093 - datasets - INFO - PyTorch version 2.1.2 available.

/opt/homebrew/Caskroom/miniconda/base/envs/discovery_child_development/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [45]:
# Load dataset sentence embeddings (all-MiniLM-L6-v2)
embeddings_all = (
    get_sentence_embeddings(
        s3_bucket=S3_BUCKET,
        filepath=VECTORS_PATH,
        filename=VECTORS_FILE,
        id="id",
    )
    .reset_index()
    # Simplify the id by removing https
    .assign(id=lambda df: df["id"].apply(lambda x: x.split("/")[-1]))
    .set_index("id")
)

In [110]:
relevant_df.query("id == 'CN-111870085-A'")

,id,text,Dataset,topics,Detection,Detection_,Management,Management_,year,country_code
4305,CN-111870085-A,An artificial intelligence crib. The invention...,Patents,"infancy, ai2, mathematics, arts, sleep, physical",0.002197,0,0.993387,1,2020,CN

## Pre-process data

In [13]:
def get_overlaps(df: pd.DataFrame, categories: list, category_column: str) -> pd.DataFrame:
    """Fetch the datapoints that have all the categories in the list

    Args:
        df (pd.DataFrame): DataFrame containing the datapoints
        categories (list): List of categories
        category_column (str): Column name that contains the categories

    Returns:
        pd.DataFrame: DataFrame containing the datapoints that have all the categories in the list
    """
    return (
        df
        .copy()
        # transform comma separated string to list, account for nulls
        .assign(**{category_column: lambda x: x[category_column].fillna('').str.split(', ')})
        # filter the rows that have all the categories in the list
        .loc[lambda x: x[category_column].apply(lambda y: set(categories).issubset(y))]
    )

In [135]:
themes = []

In [164]:
types = ["Area of learning", "Development", "Social", "General"]
topic1 = 'mobile'
topics2 = list(set(topics_df.query("Type == @types").topic.to_list()).difference([topic1]))

# for topic2 in topics2[0:1]: 
for topic2 in topics2: 

    for dataset in ["Publications", "Patents"]:

        # Get the documents that have both topics
        df = (
            get_overlaps(relevant_df, [topic1, topic2], 'topics')[['id', 'text', 'topics', 'Dataset']]
            .query("Dataset == @dataset")
            .assign(text_ = lambda x: 'ID: ' + x['id'] + ' | TEXT: ' + x['text'])
        )
        # Take 50 documents which might be most focussed on the two topics
        df = (
            df
            # shuffle
            .sample(len(df))
            # sort by number of topics
            .assign(n_topics = lambda df: df['topics'].apply(lambda x: len(x)))
            .sort_values('n_topics')
            # get the first 50
            .head(50)
        )

        topic1_name = topics_df.query("topic == @topic1").iloc[0]["name"]
        topic2_name = topics_df.query("topic == @topic2").iloc[0]["name"]

        topic1_type = topics_df.query("topic == @topic1").iloc[0]["Type"]
        topic2_type = topics_df.query("topic == @topic2").iloc[0]["Type"]

        abstract_texts = "\n\n".join(df.text_.to_list())

        gpt_message = f"You are an expert researcher on early childhood development. \
            Here are documents related to topics: Topic 1: {topic1_name} ({topic1_type}) and Topic 2: {topic2_name} ({topic2_type}). \
            Detect one to three distinct themes across these documents, that are closely related to the interaction between these two topics, and summarise these themes. \
            For each theme, write up to two sentences of summary, highlighting how the two topics overlap \
            and also two or three most interesting examples of innovations, technologies or interventions, referencing the alphanumeric ID of the document describing the example. \
            Focus on themes and examples that consider both topics together. \
            Here's an example: \n\n##Example\n\nTheme: [Theme name]\nSummary:[Summary of the theme]\nExample 1: \
            [Example of innovation, technology or intervention] (ID: [ID of the document] \nExample 2: [Example of innovation, technology or intervention] \
            (ID: [ID of the document])\n\n##Document texts\n\n {abstract_texts} \n\n##Themes\n\n"
        
        # Generate cluster descriptions
        print(f"Generating cluster themes for {topic1_name} and {topic2_name}")
        print(f"Dataset: {dataset}, number of documents: {len(df)}")
        messages = [
            {
                "role": "user",
                "content": gpt_message,
            }
        ]
        if len(df) > 0:
            chatgpt_output = client.chat.completions.create(
                model="gpt-4-turbo-2024-04-09",
                messages=messages,
                temperature=0.6,
                max_tokens=2000,
            )
            cluster_themes = chatgpt_output.choices[0].message.content
        else:
            print("No documents found for the given topics") 

        themes.append(
            {
                "topic1": topic1,
                "topic2": topic2,
                "dataset": dataset,
                "numb_docs": len(df),
                "cluster_themes": cluster_themes,
            }
        )

Generating cluster themes for Mobile and Prenatal
Dataset: Publications, number of documents: 14
2024-04-23 15:58:37,646 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Prenatal
Dataset: Patents, number of documents: 10
2024-04-23 15:58:51,082 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Labour market
Dataset: Publications, number of documents: 9
2024-04-23 15:59:09,001 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Labour market
Dataset: Patents, number of documents: 0
No documents found for the given topics
Generating cluster themes for Mobile and Community
Dataset: Publications, number of documents: 30
2024-04-23 15:59:39,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Community
Dataset: Patents, number of documents: 0
No documents found for the given topics
Generating cluster themes for Mobile and Communication and language
Dataset: Publications, number of documents: 50
2024-04-23 16:00:00,769 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Communication and language
Dataset: Patents, number of documents: 7
2024-04-23 16:00:29,184 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Cognitive development
Dataset: Publications, number of documents: 50
2024-04-23 16:00:51,158 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Cognitive development
Dataset: Patents, number of documents: 4
2024-04-23 16:01:16,699 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Mathematics
Dataset: Publications, number of documents: 47
2024-04-23 16:01:50,148 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Mathematics
Dataset: Patents, number of documents: 21
2024-04-23 16:02:20,941 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Social services
Dataset: Publications, number of documents: 30
2024-04-23 16:02:49,550 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Social services
Dataset: Patents, number of documents: 2
2024-04-23 16:03:11,297 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Inclusion
Dataset: Publications, number of documents: 18
2024-04-23 16:03:32,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Inclusion
Dataset: Patents, number of documents: 0
No documents found for the given topics
Generating cluster themes for Mobile and Preschool
Dataset: Publications, number of documents: 50
2024-04-23 16:03:55,921 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Preschool
Dataset: Patents, number of documents: 50
2024-04-23 16:04:21,611 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Sleep
Dataset: Publications, number of documents: 7
2024-04-23 16:04:47,752 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Sleep
Dataset: Patents, number of documents: 50
2024-04-23 16:05:25,329 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Special needs
Dataset: Publications, number of documents: 40
2024-04-23 16:05:53,614 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Special needs
Dataset: Patents, number of documents: 5
2024-04-23 16:06:20,458 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Parenting
Dataset: Publications, number of documents: 36
2024-04-23 16:06:42,597 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Parenting
Dataset: Patents, number of documents: 2
2024-04-23 16:07:05,479 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Literacy
Dataset: Publications, number of documents: 50
2024-04-23 16:07:31,518 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Literacy
Dataset: Patents, number of documents: 16
2024-04-23 16:08:04,402 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Expressive arts and design
Dataset: Publications, number of documents: 50
2024-04-23 16:08:26,218 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Expressive arts and design
Dataset: Patents, number of documents: 30
2024-04-23 16:08:52,289 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Physical
Dataset: Publications, number of documents: 32
2024-04-23 16:09:20,353 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Physical
Dataset: Patents, number of documents: 35
2024-04-23 16:10:07,963 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Income
Dataset: Publications, number of documents: 3
2024-04-23 16:10:24,084 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Income
Dataset: Patents, number of documents: 0
No documents found for the given topics
Generating cluster themes for Mobile and Policy
Dataset: Publications, number of documents: 9
2024-04-23 16:10:41,902 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Policy
Dataset: Patents, number of documents: 0
No documents found for the given topics
Generating cluster themes for Mobile and Personal social emotional
Dataset: Publications, number of documents: 37
2024-04-23 16:11:28,917 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Personal social emotional
Dataset: Patents, number of documents: 1
2024-04-23 16:11:46,103 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Inequalities
Dataset: Publications, number of documents: 26
2024-04-23 16:12:08,261 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Inequalities
Dataset: Patents, number of documents: 0
No documents found for the given topics
Generating cluster themes for Mobile and Infancy
Dataset: Publications, number of documents: 50
2024-04-23 16:12:34,625 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Generating cluster themes for Mobile and Infancy
Dataset: Patents, number of documents: 50
2024-04-23 16:12:57,378 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

In [169]:
df

,id,text,topics,Dataset,text_,n_topics
79,KR-101708776-B1,A cooperative child-care service system using ...,"[mobile, infancy]",Patents,ID: KR-101708776-B1 | TEXT: A cooperative chil...,2
6004,CN-211184123-U,a baby surveillance camera. The utility model ...,"[mobile, infancy]",Patents,ID: CN-211184123-U | TEXT: a baby surveillance...,2
8835,CN-206726755-U,A kind of electronics windbell of band infant ...,"[mobile, infancy]",Patents,ID: CN-206726755-U | TEXT: A kind of electroni...,2
6679,CN-107610410-A,A kind of child missing alarm. The present inv...,"[mobile, infancy]",Patents,ID: CN-107610410-A | TEXT: A kind of child mis...,2
1231,KR-20190129169-A,Device for monitoring baby&#39;s condition and...,"[mobile, infancy]",Patents,ID: KR-20190129169-A | TEXT: Device for monito...,2
3592,CN-209692931-U,The bright stove machine in bright kitchen of ...,"[mobile, infancy]",Patents,ID: CN-209692931-U | TEXT: The bright stove ma...,2
10170,CN-111166193-A,A mobile constant temperature milk storage dev...,"[mobile, infancy]",Patents,ID: CN-111166193-A | TEXT: A mobile constant t...,2
11406,WO-2015017367-A1,Bidirectional communication between an infant ...,"[mobile, infancy]",Patents,ID: WO-2015017367-A1 | TEXT: Bidirectional com...,2
10950,KR-20180129569-A,Indirect experience of Education Application b...,"[mobile, infancy]",Patents,ID: KR-20180129569-A | TEXT: Indirect experien...,2
1641,KR-200479571-Y1,Cellpfone case with tooth development period. ...,"[mobile, infancy]",Patents,ID: KR-200479571-Y1 | TEXT: Cellpfone case wit...,2
1634,RU-181733-U1,SYSTEM OF MONITORING INDICATORS OF VITAL ACTIV...,"[mobile, infancy]",Patents,ID: RU-181733-U1 | TEXT: SYSTEM OF MONITORING ...,2
10999,KR-20210092525-A,Smart Care Spoon. The present invention attach...,"[mobile, infancy]",Patents,ID: KR-20210092525-A | TEXT: Smart Care Spoon....,2
6020,CN-202637953-U,Toddler adult spiritual communication doll. Th...,"[mobile, infancy]",Patents,ID: CN-202637953-U | TEXT: Toddler adult spiri...,2
9642,CN-215954464-U,Baby monitoring device. The utility model prov...,"[mobile, infancy]",Patents,ID: CN-215954464-U | TEXT: Baby monitoring dev...,2
1236,TR-201620071-A2,Portable Baby Care Kit Feature Multi-Purpose C...,"[mobile, infancy]",Patents,ID: TR-201620071-A2 | TEXT: Portable Baby Care...,2
6503,KR-20200138968-A,A system which manages the use time of child-c...,"[mobile, infancy]",Patents,ID: KR-20200138968-A | TEXT: A system which ma...,2
11221,US-2018025655-A1,Newborn computer applications. An electronic v...,"[mobile, infancy]",Patents,ID: US-2018025655-A1 | TEXT: Newborn computer ...,2
4793,CN-207895659-U,"A baby monitor. An infant monitor, comprising ...","[mobile, infancy]",Patents,ID: CN-207895659-U | TEXT: A baby monitor. An ...,2
1044,KR-20190017449-A,location-based management method of childminde...,"[mobile, infancy]",Patents,ID: KR-20190017449-A | TEXT: location-based ma...,2
105,SG-11201900791Q-A,Touch-sensitive tablet. TOUCH-SENSITIVE TABLET...,"[mobile, infancy]",Patents,ID: SG-11201900791Q-A | TEXT: Touch-sensitive ...,2
8772,KR-20230073908-A,Mobile infant care device and infant care syst...,"[mobile, infancy]",Patents,ID: KR-20230073908-A | TEXT: Mobile infant car...,2
11015,US-2016035244-A1,Newborn computer applications. An electronic v...,"[mobile, infancy]",Patents,ID: US-2016035244-A1 | TEXT: Newborn computer ...,2
4679,CN-207136456-U,Multifunctional intellectual traveling bag and...,"[mobile, infancy]",Patents,ID: CN-207136456-U | TEXT: Multifunctional int...,2
5088,KR-20200095732-A,Bath water quality measurement system using op...,"[mobile, infancy]",Patents,ID: KR-20200095732-A | TEXT: Bath water qualit...,2
5640,CN-207115125-U,Infant&#39;s monitoring system. The utility mo...,"[mobile, infancy]",Patents,ID: CN-207115125-U | TEXT: Infant&#39;s monito...,2
6198,CN-204406607-U,A kind of intelligent apparatus of guarding ba...,"[mobile, infancy]",Patents,ID: CN-204406607-U | TEXT: A kind of intellige...,2
10141,CN-219090299-U,A feeding device for infants. The utility mode...,"[mobile, infancy]",Patents,ID: CN-219090299-U | TEXT: A feeding device fo...,2
2551,KR-20150000097-U,Babys car seat comming out moms voice. This mo...,"[mobile, infancy]",Patents,ID: KR-20150000097-U | TEXT: Babys car seat co...,2
9095,CN-205181330-U,Baby&#39;s sign monitor. The utility model pro...,"[mobile, infancy]",Patents,ID: CN-205181330-U | TEXT: Baby&#39;s sign mon...,2
2245,CN-220421917-U,A baby monitor voice playback device. The util...,"[mobile, infancy]",Patents,ID: CN-220421917-U | TEXT: A baby monitor voic...,2
8297,CN-117018460-A,A mobile phototherapy system for infants. The ...,"[mobile, infancy]",Patents,ID: CN-117018460-A | TEXT: A mobile photothera...,2
4909,CN-207490568-U,A kind of multi-functional mobile phone charge...,"[mobile, infancy]",Patents,ID: CN-207490568-U | TEXT: A kind of multi-fun...,2
2348,KR-101825183-B1,Functionality maze device using radio communic...,"[mobile, infancy]",Patents,ID: KR-101825183-B1 | TEXT: Functionality maze...,2
6793,CN-207543237-U,A kind of wireless baby monitor. The utility m...,"[mobile, infancy]",Patents,ID: CN-207543237-U | TEXT: A kind of wireless ...,2
7846,CN-205286740-U,An ambulance used for maternal and newborn res...,"[mobile, infancy]",Patents,ID: CN-205286740-U | TEXT: An ambulance used f...,2
5067,TW-D188284-S,Display graphical user interface. [Use of item...,"[mobile, infancy]",Patents,ID: TW-D188284-S | TEXT: Display graphical use...,2
7908,CN-215398555-U,Child care system and vehicle. The utility mod...,"[mobile, infancy]",Patents,ID: CN-215398555-U | TEXT: Child care system a...,2
10821,KR-20170014474-A,Method for providing English learning program ...,"[mobile, infancy]",Patents,ID: KR-20170014474-A | TEXT: Method for provid...,2
8521,CN-103646494-A,A baby kick alarm based on bluetooth technolog...,"[mobile, infancy]",Patents,ID: CN-103646494-A | TEXT: A baby kick alarm b...,2
576,TN-2016000212-A1,Remote monitoring and control system.. Device ...,"[mobile, infancy]",Patents,ID: TN-2016000212-A1 | TEXT: Remote monitoring...,2
11078,US-2018106664-A1,Smart Diaper Changing Pad. The present inventi...,"[mobile, infancy]",Patents,ID: US-2018106664-A1 | TEXT: Smart Diaper Chan...,2
5321,CN-111759021-A,A garment with a built-in heart monitor. The i...,"[mobile, infancy]",Patents,ID: CN-111759021-A | TEXT: A garment with a bu...,2
7338,CN-114027600-A,A sound and light alarm prompting device for i...,"[mobile, infancy]",Patents,ID: CN-114027600-A | TEXT: A sound and light a...,2
4903,CN-206451333-U,A monitoring system for children&#39;s diapers...,"[mobile, infancy]",Patents,ID: CN-206451333-U | TEXT: A monitoring system...,2
1293,IN-2015CH03901-A,. This invention discloses the use of mobile p...,"[mobile, infancy]",Patents,ID: IN-2015CH03901-A | TEXT: . This invention ...,2
2689,KR-102184312-B1,Bath water quality measurement system using op...,"[mobile, infancy]",Patents,ID: KR-102184312-B1 | TEXT: Bath water quality...,2
5346,CN-106263832-A,baby bowl coffee table. A tea table for a baby...,"[mobile, infancy]",Patents,ID: CN-106263832-A | TEXT: baby bowl coffee ta...,2
11012,US-11029193-B2,Smart diaper changing pad. The present inventi...,"[mobile, infancy]",Patents,ID: US-11029193-B2 | TEXT: Smart diaper changi...,2
1315,WO-2018019129-A1,Touch-sensitive tablet. A touch-sensitive tabl...,"[mobile, infancy]",Patents,ID: WO-2018019129-A1 | TEXT: Touch-sensitive t...,2
3790,CN-207055484-U,A kind of neonate&#39;s multifunctional monito...,"[mobile, infancy]",Patents,ID: CN-207055484-U | TEXT: A kind of neonate&#...,2

In [165]:
themes_df = pd.DataFrame(themes).rename(columns={'numb_docs': 'n_docs'})
# if numb_docs = 0, then make cluster_themes empty
themes_df.loc[themes_df['n_docs'] == 0, 'cluster_themes'] = ''

In [166]:
topic1

'mobile'

In [167]:
# Save json and save csv
themes_df.to_csv(OUTPUTS_DIR / f'topic_themes_{topic1}.csv', index=False)
themes_df.to_json(OUTPUTS_DIR / f'topic_themes_{topic1}.json', orient='records')

In [171]:
topics_df.to_csv(OUTPUTS_DIR / 'topics.csv', index=False)

In [118]:


# # Get cluster centroid indices
# centroids = get_cluster_centroids(cluster_df, embeddings)
# most_central = []
# for i in range(len(centroids)):
#     most_central.append(
#         get_n_most_central_vectors(embeddings, centroids[i], n=n_central)
#     )

Generating cluster themes for Data science and AI and Mathematics
Dataset: Publications, number of documents: 29
2024-04-23 12:24:09,124 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

## Summarisation