# Check geographical spread of patents and publications

In [41]:
import pandas as pd
import json
import altair as alt

from discovery_child_development import PROJECT_DIR, S3_BUCKET
from discovery_child_development.utils import plotting_utils as pu


ENRICHED_DATA_DIR = PROJECT_DIR / 'outputs/enrichments'

In [73]:
from discovery_child_development.utils.jsonl_utils import load_jsonl

In [2]:
relevant_df = pd.read_csv(ENRICHED_DATA_DIR / 'relevant_labelled_df.csv')

In [5]:
relevant_df.head(1)

,id,text,Dataset,topics,Detection,Detection_,Management,Management_,year,country_code
0,CN-107945066-A,Kindergarten intelligent control system and co...,Patents,robotics,0.625067,1,0.568404,1,2018,CN

In [20]:
patents_totals_df = (
    pd.DataFrame(json.load(open("total_patents_per_country.json", "r")))
    .astype({"publication_year": int, "total_publications": int})
    .rename(columns={"publication_year": "year"})
    .query("year >= 2013 and year < 2024")
)

## Patents

In [24]:
patents_totals_df.head(1)

   year country_code  total_publications
0  2013           AP                1094

In [29]:
counts_df = (
    relevant_df
    .query("Dataset == 'Patents'")
    .query("year >= 2013 and year < 2024")
    .groupby('country_code')
    .agg(counts=('id', 'count'))
    .reset_index()
    .assign(fraction = lambda df: df['counts'] / df['counts'].sum())
)

counts_totals_df = (
    patents_totals_df
    .groupby("country_code")
    .agg(counts=('total_publications', 'sum'))
    .reset_index()
    .assign(fraction = lambda df: df['counts'] / df['counts'].sum())    
)

In [38]:
patent_comparison = (
    counts_df
    .merge(counts_totals_df, on='country_code', suffixes=('_patents', '_totals'))
    .assign(fraction_diff = lambda df: df['fraction_patents']/df['fraction_totals'])
    .sort_values('counts_patents', ascending=False)
)

In [172]:
patent_comparison.to_csv("global_vs_data_patents.csv", index=False)

## Publications

In [43]:
(
    relevant_df
    .query("Dataset == 'Publications'")
)

,id,text,Dataset,topics,Detection,Detection_,Management,Management_,year,country_code
11534,W2146349261,The impact of pretend play on children's devel...,Publications,"arts, communication, cognitive, games, preschool",0.198959,0,0.934951,1,2013,NaN
11535,W2134744704,The Effects of Poverty on Childhood Brain Deve...,Publications,"income, neuroscience, inequality, mental_healt...",0.905183,1,0.444455,0,2013,NaN
11536,W2124222455,Investing in Preschool Programs. We summarize ...,Publications,"income, cognitive, social_services",0.175922,0,0.888656,1,2013,NaN
11537,W2022384642,Evidence for General and Domain‐Specific Eleme...,Publications,"communication, cognitive, operations",0.662059,1,0.739743,1,2013,NaN
11538,W2055043956,The role of nutrition in children's neurocogni...,Publications,"cognitive, nutrition",0.822885,1,0.677591,1,2013,NaN
...,...,...,...,...,...,...,...,...,...,...
49800,W4380048305,Trilingual families' language strategies: pote...,Publications,communication,0.401767,0,0.797585,1,2023,NaN
49801,W4385650553,The Effects of Vitamin D Supplementation on Re...,Publications,"rct, nutrition, health",0.992909,1,0.000782,0,2023,NaN
49802,W4367694030,A Study to Assess the Effectiveness of Video A...,Publications,"social_services, protection",0.002119,0,0.996927,1,2023,NaN
49803,W4380886404,Vaginal Bleeding In Prepubertal Girls-A Case S...,Publications,NaN,0.576360,1,0.154030,0,2023,NaN
49804,W4386132309,The construction and preliminary validation of...,Publications,NaN,0.744173,1,0.033589,0,2023,NaN

In [66]:
# Use requests to call OpenAlex API
import requests

url = "https://api.openalex.org/works?filter=openalex_id:W2146349261|W2134744704"
response = requests.get(url)

In [134]:
openalex_metadata = load_jsonl("publications_metadata.jsonl")
already_fetched_ids = [p['id'].split("/")[-1] for p in openalex_metadata]
print(f"Already fetched {len(already_fetched_ids)} publications")

Already fetched 38271 publications

In [133]:
# create batches
batch_size = 50

ids = relevant_df.query("Dataset == 'Publications'")['id'].tolist()
ids = [i for i in ids if i not in already_fetched_ids]

batches = [ids[i:i + batch_size] for i in range(0, len(ids), batch_size)]

print(f"Number of documents left: {len(ids)}")

with open("publications_metadata.jsonl", "a") as f:
    for i, batch in enumerate(batches):
        url = f"https://api.openalex.org/works?filter=openalex_id:{'|'.join(batch)}&per-page=50"
        response = requests.get(url)
        results_json = response.json()['results']
        # write each dict to a new line
        for result in results_json:
            f.write(json.dumps(result) + "\n")
        print(f"{i+1}/{len(batches)} batches processed")

Number of documents left: 38121
1/763 batches processed
2/763 batches processed
3/763 batches processed
4/763 batches processed
5/763 batches processed
6/763 batches processed
7/763 batches processed
8/763 batches processed
9/763 batches processed
10/763 batches processed
11/763 batches processed
12/763 batches processed
13/763 batches processed
14/763 batches processed
15/763 batches processed
16/763 batches processed
17/763 batches processed
18/763 batches processed
19/763 batches processed
20/763 batches processed
21/763 batches processed
22/763 batches processed
23/763 batches processed
24/763 batches processed
25/763 batches processed
26/763 batches processed
27/763 batches processed
28/763 batches processed
29/763 batches processed
30/763 batches processed
31/763 batches processed
32/763 batches processed
33/763 batches processed
34/763 batches processed
35/763 batches processed
36/763 batches processed
37/763 batches processed
38/763 batches processed
39/763 batches processed
40/763 batches processed
41/763 batches processed
42/763 batches processed
43/763 batches processed
44/763 batches processed
45/763 batches processed
46/763 batches processed
47/763 batches processed
48/763 batches processed
49/763 batches processed
50/763 batches processed
51/763 batches processed
52/763 batches processed
53/763 batches processed
54/763 batches processed
55/763 batches processed
56/763 batches processed
57/763 batches processed
58/763 batches processed
59/763 batches processed
60/763 batches processed
61/763 batches processed
62/763 batches processed
63/763 batches processed
64/763 batches processed
65/763 batches processed
66/763 batches processed
67/763 batches processed
68/763 batches processed
69/763 batches processed
70/763 batches processed
71/763 batches processed
72/763 batches processed
73/763 batches processed
74/763 batches processed
75/763 batches processed
76/763 batches processed
77/763 batches processed
78/763 batches processed
79/763 batches processed
80/763 batches processed
81/763 batches processed
82/763 batches processed
83/763 batches processed
84/763 batches processed
85/763 batches processed
86/763 batches processed
87/763 batches processed
88/763 batches processed
89/763 batches processed
90/763 batches processed
91/763 batches processed
92/763 batches processed
93/763 batches processed
94/763 batches processed
95/763 batches processed
96/763 batches processed
97/763 batches processed
98/763 batches processed
99/763 batches processed
100/763 batches processed
101/763 batches processed
102/763 batches processed
103/763 batches processed
104/763 batches processed
105/763 batches processed
106/763 batches processed
107/763 batches processed
108/763 batches processed
109/763 batches processed
110/763 batches processed
111/763 batches processed
112/763 batches processed
113/763 batches processed
114/763 batches processed
115/763 batches processed
116/763 batches processed
117/763 batches processed
118/763 batches processed
119/763 batches processed
120/763 batches processed
121/763 batches processed
122/763 batches processed
123/763 batches processed
124/763 batches processed
125/763 batches processed
126/763 batches processed
127/763 batches processed
128/763 batches processed
129/763 batches processed
130/763 batches processed
131/763 batches processed
132/763 batches processed
133/763 batches processed
134/763 batches processed
135/763 batches processed
136/763 batches processed
137/763 batches processed
138/763 batches processed
139/763 batches processed
140/763 batches processed
141/763 batches processed
142/763 batches processed
143/763 batches processed
144/763 batches processed
145/763 batches processed
146/763 batches processed
147/763 batches processed
148/763 batches processed
149/763 batches processed
150/763 batches processed
151/763 batches processed
152/763 batches processed
153/763 batches processed
154/763 batches processed
155/763 batches processed
156/763 batches processed
157/763 batches processed
158/763 batches processed
159/763 batches processed
160/763 batches processed
161/763 batches processed
162/763 batches processed
163/763 batches processed
164/763 batches processed
165/763 batches processed
166/763 batches processed
167/763 batches processed
168/763 batches processed
169/763 batches processed
170/763 batches processed
171/763 batches processed
172/763 batches processed
173/763 batches processed
174/763 batches processed
175/763 batches processed
176/763 batches processed
177/763 batches processed
178/763 batches processed
179/763 batches processed
180/763 batches processed
181/763 batches processed
182/763 batches processed
183/763 batches processed
184/763 batches processed
185/763 batches processed
186/763 batches processed
187/763 batches processed
188/763 batches processed
189/763 batches processed
190/763 batches processed
191/763 batches processed
192/763 batches processed
193/763 batches processed
194/763 batches processed
195/763 batches processed
196/763 batches processed
197/763 batches processed
198/763 batches processed
199/763 batches processed
200/763 batches processed
201/763 batches processed
202/763 batches processed
203/763 batches processed
204/763 batches processed
205/763 batches processed
206/763 batches processed
207/763 batches processed
208/763 batches processed
209/763 batches processed
210/763 batches processed
211/763 batches processed
212/763 batches processed
213/763 batches processed
214/763 batches processed
215/763 batches processed
216/763 batches processed
217/763 batches processed
218/763 batches processed
219/763 batches processed
220/763 batches processed
221/763 batches processed
222/763 batches processed
223/763 batches processed
224/763 batches processed
225/763 batches processed
226/763 batches processed
227/763 batches processed
228/763 batches processed
229/763 batches processed
230/763 batches processed
231/763 batches processed
232/763 batches processed
233/763 batches processed
234/763 batches processed
235/763 batches processed
236/763 batches processed
237/763 batches processed
238/763 batches processed
239/763 batches processed
240/763 batches processed
241/763 batches processed
242/763 batches processed
243/763 batches processed
244/763 batches processed
245/763 batches processed
246/763 batches processed
247/763 batches processed
248/763 batches processed
249/763 batches processed
250/763 batches processed
251/763 batches processed
252/763 batches processed
253/763 batches processed
254/763 batches processed
255/763 batches processed
256/763 batches processed
257/763 batches processed
258/763 batches processed
259/763 batches processed
260/763 batches processed
261/763 batches processed
262/763 batches processed
263/763 batches processed
264/763 batches processed
265/763 batches processed
266/763 batches processed
267/763 batches processed
268/763 batches processed
269/763 batches processed
270/763 batches processed
271/763 batches processed
272/763 batches processed
273/763 batches processed
274/763 batches processed
275/763 batches processed
276/763 batches processed
277/763 batches processed
278/763 batches processed
279/763 batches processed
280/763 batches processed
281/763 batches processed
282/763 batches processed
283/763 batches processed
284/763 batches processed
285/763 batches processed
286/763 batches processed
287/763 batches processed
288/763 batches processed
289/763 batches processed
290/763 batches processed
291/763 batches processed
292/763 batches processed
293/763 batches processed
294/763 batches processed
295/763 batches processed
296/763 batches processed
297/763 batches processed
298/763 batches processed
299/763 batches processed
300/763 batches processed
301/763 batches processed
302/763 batches processed
303/763 batches processed
304/763 batches processed
305/763 batches processed
306/763 batches processed
307/763 batches processed
308/763 batches processed
309/763 batches processed
310/763 batches processed
311/763 batches processed
312/763 batches processed
313/763 batches processed
314/763 batches processed
315/763 batches processed
316/763 batches processed
317/763 batches processed
318/763 batches processed
319/763 batches processed
320/763 batches processed
321/763 batches processed
322/763 batches processed
323/763 batches processed
324/763 batches processed
325/763 batches processed
326/763 batches processed
327/763 batches processed
328/763 batches processed
329/763 batches processed
330/763 batches processed
331/763 batches processed
332/763 batches processed
333/763 batches processed
334/763 batches processed
335/763 batches processed
336/763 batches processed
337/763 batches processed
338/763 batches processed
339/763 batches processed
340/763 batches processed
341/763 batches processed
342/763 batches processed
343/763 batches processed
344/763 batches processed
345/763 batches processed
346/763 batches processed
347/763 batches processed
348/763 batches processed
349/763 batches processed
350/763 batches processed
351/763 batches processed
352/763 batches processed
353/763 batches processed
354/763 batches processed
355/763 batches processed
356/763 batches processed
357/763 batches processed
358/763 batches processed
359/763 batches processed
360/763 batches processed
361/763 batches processed
362/763 batches processed
363/763 batches processed
364/763 batches processed
365/763 batches processed
366/763 batches processed
367/763 batches processed
368/763 batches processed
369/763 batches processed
370/763 batches processed
371/763 batches processed
372/763 batches processed
373/763 batches processed
374/763 batches processed
375/763 batches processed
376/763 batches processed
377/763 batches processed
378/763 batches processed
379/763 batches processed
380/763 batches processed
381/763 batches processed
382/763 batches processed
383/763 batches processed
384/763 batches processed
385/763 batches processed
386/763 batches processed
387/763 batches processed
388/763 batches processed
389/763 batches processed
390/763 batches processed
391/763 batches processed
392/763 batches processed
393/763 batches processed
394/763 batches processed
395/763 batches processed
396/763 batches processed
397/763 batches processed
398/763 batches processed
399/763 batches processed
400/763 batches processed
401/763 batches processed
402/763 batches processed
403/763 batches processed
404/763 batches processed
405/763 batches processed
406/763 batches processed
407/763 batches processed
408/763 batches processed
409/763 batches processed
410/763 batches processed
411/763 batches processed
412/763 batches processed
413/763 batches processed
414/763 batches processed
415/763 batches processed
416/763 batches processed
417/763 batches processed
418/763 batches processed
419/763 batches processed
420/763 batches processed
421/763 batches processed
422/763 batches processed
423/763 batches processed
424/763 batches processed
425/763 batches processed
426/763 batches processed
427/763 batches processed
428/763 batches processed
429/763 batches processed
430/763 batches processed
431/763 batches processed
432/763 batches processed
433/763 batches processed
434/763 batches processed
435/763 batches processed
436/763 batches processed
437/763 batches processed
438/763 batches processed
439/763 batches processed
440/763 batches processed
441/763 batches processed
442/763 batches processed
443/763 batches processed
444/763 batches processed
445/763 batches processed
446/763 batches processed
447/763 batches processed
448/763 batches processed
449/763 batches processed
450/763 batches processed
451/763 batches processed
452/763 batches processed
453/763 batches processed
454/763 batches processed
455/763 batches processed
456/763 batches processed
457/763 batches processed
458/763 batches processed
459/763 batches processed
460/763 batches processed
461/763 batches processed
462/763 batches processed
463/763 batches processed
464/763 batches processed
465/763 batches processed
466/763 batches processed
467/763 batches processed
468/763 batches processed
469/763 batches processed
470/763 batches processed
471/763 batches processed
472/763 batches processed
473/763 batches processed
474/763 batches processed
475/763 batches processed
476/763 batches processed
477/763 batches processed
478/763 batches processed
479/763 batches processed
480/763 batches processed
481/763 batches processed
482/763 batches processed
483/763 batches processed
484/763 batches processed
485/763 batches processed
486/763 batches processed
487/763 batches processed
488/763 batches processed
489/763 batches processed
490/763 batches processed
491/763 batches processed
492/763 batches processed
493/763 batches processed
494/763 batches processed
495/763 batches processed
496/763 batches processed
497/763 batches processed
498/763 batches processed
499/763 batches processed
500/763 batches processed
501/763 batches processed
502/763 batches processed
503/763 batches processed
504/763 batches processed
505/763 batches processed
506/763 batches processed
507/763 batches processed
508/763 batches processed
509/763 batches processed
510/763 batches processed
511/763 batches processed
512/763 batches processed
513/763 batches processed
514/763 batches processed
515/763 batches processed
516/763 batches processed
517/763 batches processed
518/763 batches processed
519/763 batches processed
520/763 batches processed
521/763 batches processed
522/763 batches processed
523/763 batches processed
524/763 batches processed
525/763 batches processed
526/763 batches processed
527/763 batches processed
528/763 batches processed
529/763 batches processed
530/763 batches processed
531/763 batches processed
532/763 batches processed
533/763 batches processed
534/763 batches processed
535/763 batches processed
536/763 batches processed
537/763 batches processed
538/763 batches processed
539/763 batches processed
540/763 batches processed
541/763 batches processed
542/763 batches processed
543/763 batches processed
544/763 batches processed
545/763 batches processed
546/763 batches processed
547/763 batches processed
548/763 batches processed
549/763 batches processed
550/763 batches processed
551/763 batches processed
552/763 batches processed
553/763 batches processed
554/763 batches processed
555/763 batches processed
556/763 batches processed
557/763 batches processed
558/763 batches processed
559/763 batches processed
560/763 batches processed
561/763 batches processed
562/763 batches processed
563/763 batches processed
564/763 batches processed
565/763 batches processed
566/763 batches processed
567/763 batches processed
568/763 batches processed
569/763 batches processed
570/763 batches processed
571/763 batches processed
572/763 batches processed
573/763 batches processed
574/763 batches processed
575/763 batches processed
576/763 batches processed
577/763 batches processed
578/763 batches processed
579/763 batches processed
580/763 batches processed
581/763 batches processed
582/763 batches processed
583/763 batches processed
584/763 batches processed
585/763 batches processed
586/763 batches processed
587/763 batches processed
588/763 batches processed
589/763 batches processed
590/763 batches processed
591/763 batches processed
592/763 batches processed
593/763 batches processed
594/763 batches processed
595/763 batches processed
596/763 batches processed
597/763 batches processed
598/763 batches processed
599/763 batches processed
600/763 batches processed
601/763 batches processed
602/763 batches processed
603/763 batches processed
604/763 batches processed
605/763 batches processed
606/763 batches processed
607/763 batches processed
608/763 batches processed
609/763 batches processed
610/763 batches processed
611/763 batches processed
612/763 batches processed
613/763 batches processed
614/763 batches processed
615/763 batches processed
616/763 batches processed
617/763 batches processed
618/763 batches processed
619/763 batches processed
620/763 batches processed
621/763 batches processed
622/763 batches processed
623/763 batches processed
624/763 batches processed
625/763 batches processed
626/763 batches processed
627/763 batches processed
628/763 batches processed
629/763 batches processed
630/763 batches processed
631/763 batches processed
632/763 batches processed
633/763 batches processed
634/763 batches processed
635/763 batches processed
636/763 batches processed
637/763 batches processed
638/763 batches processed
639/763 batches processed
640/763 batches processed
641/763 batches processed
642/763 batches processed
643/763 batches processed
644/763 batches processed
645/763 batches processed
646/763 batches processed
647/763 batches processed
648/763 batches processed
649/763 batches processed
650/763 batches processed
651/763 batches processed
652/763 batches processed
653/763 batches processed
654/763 batches processed
655/763 batches processed
656/763 batches processed
657/763 batches processed
658/763 batches processed
659/763 batches processed
660/763 batches processed
661/763 batches processed
662/763 batches processed
663/763 batches processed
664/763 batches processed
665/763 batches processed
666/763 batches processed
667/763 batches processed
668/763 batches processed
669/763 batches processed
670/763 batches processed
671/763 batches processed
672/763 batches processed
673/763 batches processed
674/763 batches processed
675/763 batches processed
676/763 batches processed
677/763 batches processed
678/763 batches processed
679/763 batches processed
680/763 batches processed
681/763 batches processed
682/763 batches processed
683/763 batches processed
684/763 batches processed
685/763 batches processed
686/763 batches processed
687/763 batches processed
688/763 batches processed
689/763 batches processed
690/763 batches processed
691/763 batches processed
692/763 batches processed
693/763 batches processed
694/763 batches processed
695/763 batches processed
696/763 batches processed
697/763 batches processed
698/763 batches processed
699/763 batches processed
700/763 batches processed
701/763 batches processed
702/763 batches processed
703/763 batches processed
704/763 batches processed
705/763 batches processed
706/763 batches processed
707/763 batches processed
708/763 batches processed
709/763 batches processed
710/763 batches processed
711/763 batches processed
712/763 batches processed
713/763 batches processed
714/763 batches processed
715/763 batches processed
716/763 batches processed
717/763 batches processed
718/763 batches processed
719/763 batches processed
720/763 batches processed
721/763 batches processed
722/763 batches processed
723/763 batches processed
724/763 batches processed
725/763 batches processed
726/763 batches processed
727/763 batches processed
728/763 batches processed
729/763 batches processed
730/763 batches processed
731/763 batches processed
732/763 batches processed
733/763 batches processed
734/763 batches processed
735/763 batches processed
736/763 batches processed
737/763 batches processed
738/763 batches processed
739/763 batches processed
740/763 batches processed
741/763 batches processed
742/763 batches processed
743/763 batches processed
744/763 batches processed
745/763 batches processed
746/763 batches processed
747/763 batches processed
748/763 batches processed
749/763 batches processed
750/763 batches processed
751/763 batches processed
752/763 batches processed
753/763 batches processed
754/763 batches processed
755/763 batches processed
756/763 batches processed
757/763 batches processed
758/763 batches processed
759/763 batches processed
760/763 batches processed
761/763 batches processed
762/763 batches processed
763/763 batches processed

## Get reference data

In [165]:
all_country_codes = [
    'AD',
    'AE',
    'AF',
    'AL',
    'AM',
    'AO',
    'AR',
    'AS',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CN',
    'CO',
    'CR',
    'CU',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FO',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GL',
    'GM',
    'GP',
    'GR',
    'GT',
    'GU',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IR',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LK',
    'LR',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MD',
    'MG',
    'MK',
    'ML',
    'MM',
    'MN',
    'MO',
    'MP',
    'MQ',
    'MR',
    'MT',
    'MU',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NC',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PR',
    'PS',
    'PT',
    'PY',
    'QA',
    'RO',
    'RS',
    'RU',
    'RW',
    'SA',
    'SC',
    'SD',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SN',
    'SR',
    'SS',
    'SV',
    'SZ',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TR',
    'TT',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'WS',
    'XK',
    'YE',
    'ZA',
    'ZM',
    'ZW'
]

In [169]:
years = [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
years = [str(y) for y in years]

counts = []

for i, country_code in enumerate(all_country_codes):
    url = f"https://api.openalex.org/works?filter=institutions.country_code:{country_code},publication_year:{'|'.join(years)}&per-page=1"
    response = requests.get(url)
    counts.append(response.json()['meta']['count'])
    print(f"Processed {i}/{len(all_country_codes)}")

Processed 0/180
Processed 1/180
Processed 2/180
Processed 3/180
Processed 4/180
Processed 5/180
Processed 6/180
Processed 7/180
Processed 8/180
Processed 9/180
Processed 10/180
Processed 11/180
Processed 12/180
Processed 13/180
Processed 14/180
Processed 15/180
Processed 16/180
Processed 17/180
Processed 18/180
Processed 19/180
Processed 20/180
Processed 21/180
Processed 22/180
Processed 23/180
Processed 24/180
Processed 25/180
Processed 26/180
Processed 27/180
Processed 28/180
Processed 29/180
Processed 30/180
Processed 31/180
Processed 32/180
Processed 33/180
Processed 34/180
Processed 35/180
Processed 36/180
Processed 37/180
Processed 38/180
Processed 39/180
Processed 40/180
Processed 41/180
Processed 42/180
Processed 43/180
Processed 44/180
Processed 45/180
Processed 46/180
Processed 47/180
Processed 48/180
Processed 49/180
Processed 50/180
Processed 51/180
Processed 52/180
Processed 53/180
Processed 54/180
Processed 55/180
Processed 56/180
Processed 57/180
Processed 58/180
Processed 59/180
Processed 60/180
Processed 61/180
Processed 62/180
Processed 63/180
Processed 64/180
Processed 65/180
Processed 66/180
Processed 67/180
Processed 68/180
Processed 69/180
Processed 70/180
Processed 71/180
Processed 72/180
Processed 73/180
Processed 74/180
Processed 75/180
Processed 76/180
Processed 77/180
Processed 78/180
Processed 79/180
Processed 80/180
Processed 81/180
Processed 82/180
Processed 83/180
Processed 84/180
Processed 85/180
Processed 86/180
Processed 87/180
Processed 88/180
Processed 89/180
Processed 90/180
Processed 91/180
Processed 92/180
Processed 93/180
Processed 94/180
Processed 95/180
Processed 96/180
Processed 97/180
Processed 98/180
Processed 99/180
Processed 100/180
Processed 101/180
Processed 102/180
Processed 103/180
Processed 104/180
Processed 105/180
Processed 106/180
Processed 107/180
Processed 108/180
Processed 109/180
Processed 110/180
Processed 111/180
Processed 112/180
Processed 113/180
Processed 114/180
Processed 115/180
Processed 116/180
Processed 117/180
Processed 118/180
Processed 119/180
Processed 120/180
Processed 121/180
Processed 122/180
Processed 123/180
Processed 124/180
Processed 125/180
Processed 126/180
Processed 127/180
Processed 128/180
Processed 129/180
Processed 130/180
Processed 131/180
Processed 132/180
Processed 133/180
Processed 134/180
Processed 135/180
Processed 136/180
Processed 137/180
Processed 138/180
Processed 139/180
Processed 140/180
Processed 141/180
Processed 142/180
Processed 143/180
Processed 144/180
Processed 145/180
Processed 146/180
Processed 147/180
Processed 148/180
Processed 149/180
Processed 150/180
Processed 151/180
Processed 152/180
Processed 153/180
Processed 154/180
Processed 155/180
Processed 156/180
Processed 157/180
Processed 158/180
Processed 159/180
Processed 160/180
Processed 161/180
Processed 162/180
Processed 163/180
Processed 164/180
Processed 165/180
Processed 166/180
Processed 167/180
Processed 168/180
Processed 169/180
Processed 170/180
Processed 171/180
Processed 172/180
Processed 173/180
Processed 174/180
Processed 175/180
Processed 176/180
Processed 177/180
Processed 178/180
Processed 179/180

In [170]:
pd.DataFrame({
    "country_code": all_country_codes,
    "total_publications": counts
}).to_json("total_publications_per_country.json", orient="records")

In [171]:
pd.DataFrame({
    "country_code": all_country_codes,
    "total_publications": counts
})

    country_code  total_publications
0             AD                 385
1             AE              104268
2             AF                5359
3             AL               13335
4             AM               17560
..           ...                 ...
175           XK                8636
176           YE               17385
177           ZA              363382
178           ZM               14568
179           ZW               18532

[180 rows x 2 columns]