In [1]:
from discovery_child_development.getters import patents, openalex

2024-05-31 12:28:06,733 - botocore.credentials - INFO - Found credentials in environment variables.
2024-05-31 12:28:07,950 - datasets - INFO - PyTorch version 2.1.2 available.

/opt/homebrew/Caskroom/miniconda/base/envs/discovery_child_development/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## OpenAlex checking

In [10]:
latest_df = openalex.get_abstracts(input_path = 'data/openAlex/openalex_works_concepts_20240531_125353/')

In [3]:
old_df = openalex.get_abstracts(input_path = 'data/openAlex/openalex_works_concepts_20240229_105641/')

In [11]:
len(latest_df), len(old_df)

(158252, 116350)

In [225]:
text = 'Results From a Controlled Study of the iPad Fractions Game Motion Mat'
old_df[old_df.title.str.contains(text)]

Empty DataFrame
Columns: [id, title, abstract, text]
Index: []

In [226]:
latest_df[latest_df.title.str.contains(text)]

Empty DataFrame
Columns: [id, title, abstract, text]
Index: []

In [20]:
latest_df

,id,title,abstract,text
0,https://openalex.org/W2146349261,The impact of pretend play on children's devel...,Pretend play has been claimed to be crucial to...,The impact of pretend play on children's devel...
1,https://openalex.org/W2134744704,The Effects of Poverty on Childhood Brain Deve...,IMPORTANCE The study provides novel data to in...,The Effects of Poverty on Childhood Brain Deve...
2,https://openalex.org/W2124222455,Investing in Preschool Programs,We summarize the available evidence on the ext...,Investing in Preschool Programs. We summarize ...
3,https://openalex.org/W1993392684,Developmental Changes in Executive Functioning,Although early studies of executive functionin...,Developmental Changes in Executive Functioning...
4,https://openalex.org/W2022384642,Evidence for General and Domain‐Specific Eleme...,This study evaluates a model for considering d...,Evidence for General and Domain‐Specific Eleme...
...,...,...,...,...
191551,https://openalex.org/W2084542952,Prognosis and therapy of myasthenia gravis in ...,Objectives: To investigate the influence of on...,Prognosis and therapy of myasthenia gravis in ...
191553,https://openalex.org/W3163075822,Diarrea crónica en el niño,Prolongued diarrhea is defined as the increase...,Diarrea crónica en el niño. Prolongued diarrhe...
191554,https://openalex.org/W4252040904,Nonstarch Polysaccharides from Food Grains: ei...,Plant carbohydrates can be broadly classied in...,Nonstarch Polysaccharides from Food Grains: ei...
191556,https://openalex.org/W4251755310,Presidential lectureSpecial lectureEducational...,会長講演 第 1 日／第 1 会場／10：40～11：40 司会 里宇 明元 活動の臨床とし...,Presidential lectureSpecial lectureEducational...
191557,https://openalex.org/W2999641442,Wala Tayong Sasantuhin,Although downloading and printing of the artic...,Wala Tayong Sasantuhin. Although downloading a...

In [263]:
import requests

BASE_URL = "https://api.openalex.org/works"
BASE_KEYWORD = "(child)"
KEYWORDS_DATA = "(math app OR math apps)"
# QUERY = f'{BASE_URL}?search=(abstract:{KEYWORDS_DATA} AND abstract:{BASE_KEYWORD}) OR (title:
# {KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
QUERY = f'{BASE_URL}?search=(title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
response = requests.get(f"{QUERY}&per-page=100")
j=-1
response.json()['meta']

{'count': 1355,
 'db_response_time_ms': 244,
 'page': 1,
 'per_page': 100,
 'groups_count': None}

In [266]:
j+=1
_id = response.json()['results'][j]['id']
print(_id)
print(response.json()['results'][j]['publication_year'])
print(response.json()['results'][j]['title'])

https://openalex.org/W1041173458
2015
Tablet use in schools: a critical review of the evidence for learning outcomes

In [258]:
BASE_KEYWORD = "(child)"
KEYWORDS_DATA = "('math app' OR 'math apps')"
# QUERY = f'{BASE_URL}?search=(abstract:{KEYWORDS_DATA} AND abstract:{BASE_KEYWORD}) OR (title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
QUERY = f'{BASE_URL}?search=(title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
response = requests.get(f"{QUERY}&per-page=100")
j=-1
response.json()['meta']

{'count': 1355,
 'db_response_time_ms': 130,
 'page': 1,
 'per_page': 100,
 'groups_count': None}

In [276]:
BASE_URL = "https://api.openalex.org/works"
BASE_KEYWORD = '("child")'
KEYWORDS_DATA = "('math app' OR 'math apps')"
# QUERY = f'{BASE_URL}?search=(abstract:{KEYWORDS_DATA} AND abstract:{BASE_KEYWORD}) OR (title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
QUERY = f'{BASE_URL}?search=(title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
response = requests.get(f"{QUERY}&per-page=100")
j=-1
response.json()['meta']

{'count': 1355,
 'db_response_time_ms': 103,
 'page': 1,
 'per_page': 100,
 'groups_count': None}

In [375]:
BASE_KEYWORD = '("math")'
KEYWORDS_DATA = '("apps")'
# QUERY = f'{BASE_URL}?search=(abstract:{KEYWORDS_DATA} AND abstract:{BASE_KEYWORD}) OR (title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
QUERY = f'{BASE_URL}?search=(title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
response = requests.get(f"{QUERY}&per-page=100")
j=-1
response.json()['meta']

{'count': 3217,
 'db_response_time_ms': 287,
 'page': 1,
 'per_page': 100,
 'groups_count': None}

In [381]:
j+=1
_id = response.json()['results'][j]['id']
print(_id)
print(response.json()['results'][j]['publication_year'])
print(response.json()['results'][j]['title'])

https://openalex.org/W2798796321
2017
From hypertext to hyperdimension Neptunia: The future of VR visual novels: The potentials of new technologies for branching-path narrative games

In [61]:
latest_df.query("id == @_id")

Empty DataFrame
Columns: [id, title, abstract, text]
Index: []

In [74]:
query = "https://api.openalex.org/works?search=(abstract:(child OR infant OR baby OR prenatal OR pregnancy OR toddler OR family OR parent OR pupil) AND abstract:(chatgpt OR income OR 'early childhood education' OR 'artificial intelligence' OR assess OR assessment OR 'augmented reality' OR autism OR behaviour OR development OR 'eye tracking' OR genetics OR income OR learning OR 'learning environment' OR monitor OR psychotherapy OR 'randomised controlled trials' OR robotics OR 'social media' OR 'social services' OR 'special need' OR technology OR 'virtual reality' OR wearable OR app OR apps OR mobile OR math OR maths OR literacy OR reading OR read OR language OR communication OR 'machine learning' OR 'deep learning' OR 'generative ai' OR speech)) OR (title:(child OR infant OR baby OR prenatal OR pregnancy OR toddler OR family OR parent OR pupil) AND title:(chatgpt OR income OR 'early childhood education' OR 'artificial intelligence' OR assess OR assessment OR 'augmented reality' OR autism OR behaviour OR development OR 'eye tracking' OR genetics OR income OR learning OR 'learning environment' OR monitor OR psychotherapy OR 'randomised controlled trials' OR robotics OR 'social media' OR 'social services' OR 'special need' OR technology OR 'virtual reality' OR wearable OR app OR apps OR mobile OR math OR maths OR literacy OR reading OR read OR language OR communication OR 'machine learning' OR 'deep learning' OR 'generative ai' OR speech))"

In [288]:
response = requests.get(f"{query}&per-page=20&filter=publication_year:2021,type:article")
response.json()['meta']

{'count': 5938,
 'db_response_time_ms': 1300,
 'page': 1,
 'per_page': 20,
 'groups_count': None}

In [365]:
TECH_KEYWORDS = '("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")'
CHILD_KEYWORDS = '("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents")'
query2 = f'https://api.openalex.org/works?search=(abstract:{CHILD_KEYWORDS} AND abstract:{TECH_KEYWORDS}) OR (title:{CHILD_KEYWORDS} AND title:{TECH_KEYWORDS})'

In [370]:
response = requests.get(f"{query2}&filter=publication_year:>2016,type:article")
response.json()['meta']

{'count': 901273,
 'db_response_time_ms': 1713,
 'page': 1,
 'per_page': 20,
 'groups_count': None}

In [317]:
j=-1

In [338]:
j+=1
_id = response.json()['results'][j]['id']
print(_id)
print(response.json()['results'][j]['publication_year'])
print(response.json()['results'][j]['title'])

IndexError: list index out of range

In [154]:
response = requests.get(f"{query2}&per-page=20&filter=publication_year:>2012,type:article")
response.json()['meta']

{'count': 1402816,
 'db_response_time_ms': 2651,
 'page': 1,
 'per_page': 20,
 'groups_count': None}

In [131]:
j = 19
_id = response.json()['results'][j]['id']
print(_id)
print(response.json()['results'][j]['publication_year'])
print(response.json()['results'][j]['title'])

https://openalex.org/W3207107988
2021
Perfluoroalkyl substances exposure and immunity, allergic response, infection, and asthma in children: review of epidemiologic studies

In [289]:
CHILD_KEYWORDS_WRONG = "(child OR infant OR baby OR prenatal OR pregnancy OR toddler OR family OR parent OR pupil OR children OR babies OR toddlers OR families OR parents)"

TECH_KEYWORDS_WRONG = '(chatgpt OR income OR "early childhood education" OR "artificial intelligence" OR assess OR assessment OR "augmented reality" OR autism OR behaviour OR development OR "eye tracking" OR genetics OR income OR learning OR "learning environment" OR monitor OR psychotherapy OR "randomised controlled trials" OR robotics OR "social media" OR "social services" OR "special need" OR technology OR "virtual reality" OR wearable OR app OR apps OR mobile OR math OR maths OR literacy OR reading OR read OR language OR communication OR "machine learning" OR "deep learning" OR "generative ai" OR speech)'

query_wrong = f'https://api.openalex.org/works?search=(abstract:{CHILD_KEYWORDS_WRONG} AND abstract:{TECH_KEYWORDS_WRONG}) OR (title:{CHILD_KEYWORDS_WRONG} AND title:{TECH_KEYWORDS_WRONG})'

In [290]:
response = requests.get(f"{query_wrong}&per-page=20&filter=publication_year:2021,type:article")
response.json()['meta']

{'count': 94617,
 'db_response_time_ms': 1536,
 'page': 1,
 'per_page': 20,
 'groups_count': None}

In [291]:
j=-1

In [313]:
j+=1
_id = response.json()['results'][j]['id']
print(_id)
print(response.json()['results'][j]['publication_year'])
print(response.json()['results'][j]['title'])

IndexError: list index out of range

In [342]:
from discovery_child_development.utils import openalex_utils
import importlib
importlib.reload(openalex_utils);
from discovery_child_development import S3_BUCKET, config

In [343]:
API_ROOT = config["openalex_keywords_api_root"]
KEYWORDS = config["openalex_keywords"]
YEARS = config["openalex_years"]

In [395]:
list(range(2017,2024))

[2017, 2018, 2019, 2020, 2021, 2022, 2023]

In [347]:
API_ROOT

'https://api.openalex.org/works?search=(abstract:(child OR infant OR baby OR prenatal OR pregnancy OR toddler OR family OR parent OR pupil) AND abstract:(KEYWORD)) OR (title:(child OR infant OR baby OR prenatal OR pregnancy OR toddler OR family OR parent OR pupil) AND title:(KEYWORD))'

In [403]:
TECH_KEYWORDS = '("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")'
CHILD_KEYWORDS = '("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils")'
QUERY = f'https://api.openalex.org/works?search=(abstract:{CHILD_KEYWORDS} AND abstract:{TECH_KEYWORDS}) OR (title:{CHILD_KEYWORDS} AND title:{TECH_KEYWORDS})'
QUERIES = [f"{QUERY}&filter=publication_year:{year},type:article" for year in YEARS]

In [405]:
QUERIES

['https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2013,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2014,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2015,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2016,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2017,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2018,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2019,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2020,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2021,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2022,type:article',

In [404]:
response = requests.get(f"{QUERY}&filter=publication_year:>2016,type:article")
response.json()['meta']

{'count': 925595,
 'db_response_time_ms': 3541,
 'page': 1,
 'per_page': 25,
 'groups_count': None}

In [389]:
response = requests.get(f"{QUERY}&filter=publication_year:{year},type:article" for year in YEARS)
response.json()['meta']

{'count': 93609,
 'db_response_time_ms': 1901,
 'page': 1,
 'per_page': 25,
 'groups_count': None}

## Processing openalex json downloads

In [1]:
import json
from discovery_child_development import PROJECT_DIR

In [2]:
from discovery_child_development.utils import openalex_utils

In [3]:
import pandas as pd

In [4]:
for i in [1, 2, 3, 4, 5, 6]:
    data = json.load(open(PROJECT_DIR / f'inputs/data/openalex_keywords/json/output_{i}.json'))
    data_df = pd.DataFrame(data)

    _data_df = (
        data_df[['id', 'publication_year', 'title', 'abstract_inverted_index', 'authorships', 'language']]
        .dropna(subset=['abstract_inverted_index'])
        .dropna(subset=['title'])
        .query("language == 'en'")
        .assign(abstract = lambda df: df.abstract_inverted_index.apply(openalex_utils.deinvert_abstract))
        .drop(columns=['abstract_inverted_index'])
    )

    _data_df.to_parquet(PROJECT_DIR / f'inputs/data/openalex_keywords/parquet/output_{i}.parquet', index=False)

## Checking openalex data

In [3]:
import pandas as pd
from nesta_ds_utils.loading_saving import S3
from discovery_child_development import S3_BUCKET, PROJECT_DIR

OUTPUT_FILENAME = "keywords_31May2024"
ENRICHED_DATA_DIR = PROJECT_DIR / "outputs/enrichments"

In [4]:
dfs = []
for i in list(range(0,7)):
    dfs.append(
        S3.download_obj(
            S3_BUCKET,
            path_from = f"data/outputs/binary_classifier/{OUTPUT_FILENAME}_{i}.parquet",
            download_as="dataframe",
        )
        .query("predictions == 1")
        .assign(source = "openalex")
    )

print(len(dfs))
dfs = pd.concat(dfs)
dfs.to_csv(ENRICHED_DATA_DIR / "openalex_relevance_labels_only_relevant.csv", index=False)

2024-06-03 12:37:11,661 - botocore.credentials - INFO - Found credentials in environment variables.

7

In [5]:
print(len(dfs))

37975

In [ ]:
pd.set_option('display.max_colwidth', 300)

In [20]:
dfs.sample()

,id,text,predictions,source
82194,https://openalex.org/W2941142296,"FAMILIARIZING PRESCHOOL CHILDREN WITH THE «CHILD IN SOCIETY» EDUCATIONAL PROFILE IN MODERN REALITIES. NEVMERZHYTSKA Olena – Doctor of Pedagogical Sciences, Associate Professor, Professor of the General Pedagogy and Preschool Education Department, Drohobych Ivan Franko State Pedagogical Universit...",1,openalex

## Merging openalex data

In [4]:
import utils
import pandas as pd

In [3]:
openalex_df = utils.load_openalex_data()
patents_df = utils.load_patents_data()
funding_data = utils.load_ukri_data()
cb_data = utils.load_crunchbase_data()

In [5]:
len(openalex_df), len(patents_df), len(funding_data), len(cb_data)

(70128, 26034, 1086, 3773)

In [6]:
pd.concat([openalex_df, patents_df, funding_data, cb_data], ignore_index=True).to_csv('all_data.csv', index=False)

In [33]:
openalex_df

,id,text,dataset,topics,year,country_code
0,W2102925803,"Interventions for increasing fruit and vegetable consumption in children aged five years and under. Insufficient consumption of fruits and vegetables in childhood increases the risk of future non-communicable diseases, including cardiovascular disease. Testing the effects of interventions to inc...",openalex,"rct, nutrition, health",2020.0,[AU]
1,W3097547541,"Does Household Income Affect children’s Outcomes? A Systematic Review of the Evidence. Abstract There is abundant evidence that children in low income households do less well than their peers on a range of developmental outcomes. However, there is continuing uncertainty about how far money itsel...",openalex,"mental_health, income, rct, health",2020.0,[GB]
2,W3033628182,"Global burden of preterm birth. Abstract Preterm birth is a live birth that occurs before 37 completed weeks of pregnancy. Approximately 15 million babies are born preterm annually worldwide, indicating a global preterm birth rate of about 11%. With 1 million children dying due to preterm birth ...",openalex,"prenatal, infancy",2020.0,[US]
3,W3106925869,"Screening tools for early identification of children with developmental delay in low- and middle-income countries: a systematic review. To systematically review, identify and report the screening tools used for early identification of developmental delay in low- and middle-income countries.Syste...",openalex,"nontech, communication, send, infancy",2020.0,"[AU, BD]"
4,W4234954338,"Strategies to improve the implementation of healthy eating, physical activity and obesity prevention policies, practices or programmes within childcare services. Despite the existence of effective interventions and best-practice guideline recommendations for childcare services to implement evide...",openalex,"rct, policy, nutrition, health",2020.0,[AU]
...,...,...,...,...,...,...
70918,W4385782293,Virtual assessment of stress reactivity in young children: Practical guidelines &amp;amp; lessons learned. Measures of stress reactivity and coping are critical in developmental research inchildren. Such measures assist in identifying psycho-physiological abnormalities andaid in developing inter...,openalex,"operations, mental_health",2023.0,[CA]
70919,W4365815550,"Infant-Directed Communication: Examining the many dimensions of everyday caregiver-infant interactions. Everyday caregiver-infant interactions are dynamic and multidimensional. However, existing research underestimates the dimensionality of infants’ experiences, often focusing on one or two comm...",openalex,"infancy, communication",2023.0,[US]
70920,W4385765606,"It's not just what we don't know: The mapping problem in the acquisition of negation. How do learners learn what no and not mean when they are only presented with what is? Given its complexity, abstractness, and roles in logic, truth-functional negation might be a conceptual accomplishment. As a...",openalex,communication,2023.0,"[US, GB]"
70921,W4379911316,"Prenatal diagnosis of Persistent Left Superior Vena Cava draining into a cervical hemangioma: Case report and literature report. Introduction Vascular anomalies are alterations in angiogenesis and endothelial proliferation, respectively, that can generate not only aesthetic problems, but also fu...",openalex,infancy,2023.0,"[CO, BE]"
70922,W4380048305,"Trilingual families' language strategies: potential predictors and effect on trilingual exposure. Family language strategies are approaches that parents adopt for language use with their multilingual children. In bilingual contexts, these strategies influence children’s language exposure and dev...",openalex,communication,2023.0,[US]

In [35]:
# Manual additions to the data
manual_dict = [
    {
        "id":"W2580979658",
        "text": "Closing the gap: Efficacy of a tablet intervention to support the development of early mathematical skills in UK primary school children",
        "dataset": "openalex",
        "topics": "mathematics, mobile",
        "year": 2017,
        "country_code": "['GB']"
    },
    {
        "id":"W2810138508",
        "text": "Raising early achievement in math with interactive apps: A randomized control trial.",
        "dataset": "openalex",
        "topics": "mathematics, mobile",
        "year": 2017,
        "country_code": "['GB']"
    },   
    {
        "id":"W4378082651",
        "text": "Understanding how educational maths apps can enhance learning: A content analysis and qualitative comparative analysis",
        "dataset": "openalex",
        "topics": "mathematics, mobile",
        "year": 2023,
        "country_code": "['GB']"
    },      
    {
        "id":"W4315782119",
        "text": "App-based support for parental self-efficacy in the first 1,000 days: A randomized control trial",
        "dataset": "openalex",
        "topics": "parenting2, mobile",
        "year": 2023,
        "country_code": "['GB']"
    },  
    {
        "id":"W3005991893",
        "text": "Language counts when learning mathematics with interactive apps",
        "dataset": "openalex",
        "topics": "mathematics, literacy, mobile",
        "year": 2020,
        "country_code": "['GB']"
    },               
]
pd.DataFrame(manual_dict).to_csv(ENRICHED_DATA_DIR / "openalex_manual_additions.csv", index=False)